FROM python:3.5
MAINTAINER Ian Auld <imauld@gmail.com>

RUN mkdir /app
COPY requirements.txt /app/requirements.txt
RUN python -m pip install --upgrade pip && \
    python -m venv /venv && \ 
    /venv/bin/pip install -r /app/requirements.txt

