# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import alerts_pb2 as alerts__pb2


class AlertsStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get_alerts_for_user = channel.unary_unary(
        '/alerts.Alerts/get_alerts_for_user',
        request_serializer=alerts__pb2.GetAlertsForUserRequest.SerializeToString,
        response_deserializer=alerts__pb2.GetAlertsForUserResponse.FromString,
        )
    self.mark_alert_seen = channel.unary_unary(
        '/alerts.Alerts/mark_alert_seen',
        request_serializer=alerts__pb2.MarkAlertSeenRequest.SerializeToString,
        response_deserializer=alerts__pb2.MarkAlertSeenResponse.FromString,
        )
    self.send_alert = channel.unary_unary(
        '/alerts.Alerts/send_alert',
        request_serializer=alerts__pb2.SendAlertRequest.SerializeToString,
        response_deserializer=alerts__pb2.SendAlertResponse.FromString,
        )


class AlertsServicer(object):

  def get_alerts_for_user(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def mark_alert_seen(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def send_alert(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AlertsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get_alerts_for_user': grpc.unary_unary_rpc_method_handler(
          servicer.get_alerts_for_user,
          request_deserializer=alerts__pb2.GetAlertsForUserRequest.FromString,
          response_serializer=alerts__pb2.GetAlertsForUserResponse.SerializeToString,
      ),
      'mark_alert_seen': grpc.unary_unary_rpc_method_handler(
          servicer.mark_alert_seen,
          request_deserializer=alerts__pb2.MarkAlertSeenRequest.FromString,
          response_serializer=alerts__pb2.MarkAlertSeenResponse.SerializeToString,
      ),
      'send_alert': grpc.unary_unary_rpc_method_handler(
          servicer.send_alert,
          request_deserializer=alerts__pb2.SendAlertRequest.FromString,
          response_serializer=alerts__pb2.SendAlertResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'alerts.Alerts', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
